### ISSUE TITLE
InlineVerifier cleanup tracking

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/ghostferry#126]
- [ ] Remove the "hack" of `f.inlineVerifier` on `Ferry` and make it more integrated into Ferry directly.
     - Possibly review the `Verifier` interface to see if it needs to be extended or removed.
- [ ] Consider removing `currentRowCount` from BinlogVerifyStore.

**Comment by xliang6** [comment]
Keeping some notes about the following task as I go:
- [ ]  Disallow interrupt after FlushBinlog.

I found that the shop mover code is already checking if it's in the cutover phase [here](https://github.com/Shopify/shopify/blob/6e59d50b154642fa055029677b4a47685c03d8e9/components/pod_orchestrator/shop_mover/ghostferry.rb#L213) before it forwards the SIGTERM to ghostferry. During the cutover phase, the shop mover acquires both the exclusive global lock and the exclusive shop lock, and will not forward the SIGTERM signal to ghostferry. In the future, we might be able to allow such a signal during the cutover phase if we can release these locks properly and set the state to `interrupted`?

My question next is: Is it necessary to change [the DumpStateOnSignal behavior in ghostferry](https://github.com/Shopify/ghostferry/blob/master/ferry.go#L559) to also check for these signals and ignore them during the cutover phase? Is there a reason why ghostferry can't handle an interruption during the cutover phase? If so, what is it? Is it possible to check this scenario with the TLA+ model?
